### ISSUE TITLE
Player Respawn 1.7.1

### ISSUE THREAD

**Issue by EBS-DarkD** [jaredballou/insurgency-sourcemod#11]
Have had a rocky ride trying to get this to work over the last few days...

Initial problem was giving me the same error as FlyingAce015 had, it also needs insurgency.smx which isn't listed in the dependencies

After adding insurgency.smx and listed dependencies, I then got the following

[SM] Exception reported: Plugin not runnable
[SM] Call stack trace:
[SM] Unable to load plugin "insurgency.smx": Required extension "SMJansson" file("smjansson.ext") not running
[SM] Exception reported: Plugin owning this native is currently paused.
[SM] Blaming plugin: respawn.smx
[SM] Call stack trace:
[SM]   [0] Ins_ObjectiveResource_GetProp
[SM]   [1] Line 322, respawn.sp::Event_PlayerDeath()

After finding SMJansson, adding it and restarting, I was still getting the same error until I added "sm exts load smjansson" to my server.cfg as SMJansson wouldn't autostart for some reason.

Now, the respawn works for 1 round, then next round I see the following error
[SM] Exception reported: Invalid timer handle 3ac400a0 (error 3)
[SM] Blaming plugin: respawn.smx
[SM] Call stack trace:
[SM]   [0] KillTimer
[SM]   [1] Line 348, respawn.sp::KillRespawnTimer()
[SM]   [2] Line 355, respawn.sp::CreateRespawnTimer()
[SM]   [3] Line 339, respawn.sp::Event_PlayerDeath()

Manual respawn from the admin menu is working, it's just the auto-respawn that's not.

I'm currently trying to use this in co-op to respawn bots during counter attacks and end of round. My cfg is currently set as follows (for testing)

sm_respawn_enabled "1" 
sm_respawn_count "0"  
sm_respawn_count_team2 "1" 
sm_respawn_count_team3 "1" 
sm_respawn_delay "1.0" 
sm_respawn_counterattack "1" 
sm_respawn_final_counterattack "2" 
sm_respawn_reset_each_objective "1" 
sm_respawn_reset_each_round "1" 

Can you advise 
If this will work in co-op or was it meant for pvp? 
If it should work in co-op, which team is the insurgent team?
What can I do to resolve the KillTimer error?

I'm also liking the extra info in the logs since getting insurgency.smx working

**Comment by jaredballou** [comment]
This is a result of my adding theater parsing features to the Insurgency library. I am breaking thos out to avoid this issue, and the 1.3.1 release I will be updating today resolves this issue.

**Comment by EBS-DarkD** [comment]
Thanks for looking into it, I would have tested sooner but works been getting in the way!
I've updated all the files and dependencies and my respawn.cfg is below

sm_respawn_count                "0"   // Respawn all players this many times - Default: "0"
sm_respawn_count_team2          "-1"  // Respawn all Team 2 players this many times - Default: "-1"
sm_respawn_count_team3          "1"   // Respawn all Team 3 players this many times - Default: "-1"
sm_respawn_counterattack        "1"   // Respawn during counterattack? (0: no, 1: yes, 2: infinite) - Default: "0"
sm_respawn_delay                "1.0" // How many seconds to delay the respawn - Default: "1.0"
sm_respawn_enabled              "1"   // Automatically respawn players when they die; 0 - disabled, 1 - enabled - Default: "0"
sm_respawn_final_counterattack  "1"   // Respawn during final counterattack? (0: no, 1: yes, 2: infinite) - Default: "0"
sm_respawn_reset_each_objective "1"   // Reset player respawn counts each objective - Default: "1"
sm_respawn_reset_each_round     "1"   // Reset player respawn counts each round - Default: "1"

It works ok for first objective, repawning the bots no problem but after that, I see this in the console.

L 01/30/2016 - 09:22:59: [SM] Native "KillTimer" reported: Invalid timer handle 19e009b (error 1)
L 01/30/2016 - 09:22:59: [SM] Displaying call stack trace for plugin "respawn.smx":
L 01/30/2016 - 09:22:59: [SM]   [0]  Line 348, respawn.sp::KillRespawnTimer()
L 01/30/2016 - 09:22:59: [SM]   [1]  Line 355, respawn.sp::CreateRespawnTimer()
L 01/30/2016 - 09:22:59: [SM]   [2]  Line 339, respawn.sp::Event_PlayerDeath()
L 01/30/2016 - 09:22:59: [SM] Native "KillTimer" reported: Invalid timer handle 19e009b (error 1)
L 01/30/2016 - 09:22:59: [SM] Displaying call stack trace for plugin "respawn.smx":
L 01/30/2016 - 09:22:59: [SM]   [0]  Line 348, respawn.sp::KillRespawnTimer()
L 01/30/2016 - 09:22:59: [SM]   [1]  Line 355, respawn.sp::CreateRespawnTimer()
L 01/30/2016 - 09:22:59: [SM]   [2]  Line 339, respawn.sp::Event_PlayerDeath()

This continued for the rest of the objectives and into the next map

After a server restart, again it's good for the first objective but goes sour after that

L 01/30/2016 - 09:45:13: [SM] Native "KillTimer" reported: Invalid timer handle 138009c (error 3)
L 01/30/2016 - 09:45:13: [SM] Displaying call stack trace for plugin "respawn.smx":
L 01/30/2016 - 09:45:13: [SM]   [0]  Line 348, respawn.sp::KillRespawnTimer()
L 01/30/2016 - 09:45:13: [SM]   [1]  Line 355, respawn.sp::CreateRespawnTimer()
L 01/30/2016 - 09:45:13: [SM]   [2]  Line 339, respawn.sp::Event_PlayerDeath()
L 01/30/2016 - 09:45:13: [SM] Native "KillTimer" reported: Invalid timer handle 138009c (error 3)
L 01/30/2016 - 09:45:13: [SM] Displaying call stack trace for plugin "respawn.smx":
L 01/30/2016 - 09:45:13: [SM]   [0]  Line 348, respawn.sp::KillRespawnTimer()
L 01/30/2016 - 09:45:13: [SM]   [1]  Line 355, respawn.sp::CreateRespawnTimer()
L 01/30/2016 - 09:45:13: [SM]   [2]  Line 339, respawn.sp::Event_PlayerDeath()

Sometimes it's showing error1, sometimes it's error 3
Have also upped sm_respawn_count_team3 and again it works for the first respawn of a player after a server start but errors after that

**Comment by EBS-DarkD** [comment]
A couple of questions.
If I just want the bots to spawn infinitely on the counter and final counter, if I set
sm_respawn_counterattack        "2"
sm_respawn_final_counterattack  "2"
what value would I need to set the sm_respawn_count_team to?

Also what is the rational of setting the default setting
sm_respawn_count_team2          "-1"
instead of 
sm_respawn_count_team2          "0"

**Comment by EBS-DarkD** [comment]
After a recent rebuild of the server, I've revisited this on a clean build with fresh files and am still getting the same error. It reports the error on each death and will only respawn each player/bot once. Needs a server restart before the plugin will work again. Manual respawn from the admin menu works.

Only thing I can think of is I'm running SourceMod Version: 1.7.3-dev+5275 which may be an older version than yours

**Comment by EBS-DarkD** [comment]
Upgraded to 1.8.1 and moved to thread https://github.com/jaredballou/insurgency-sourcemod/issues/20
